### ISSUE TITLE
Error: Client error: (429) RESOURCE_EXHAUSTED

### ISSUE THREAD

**Issue by irfanalidv** [r-lib/gargle#146]
---

<img width="1013" alt="Screenshot 2020-06-17 at 5 32 41 PM" src="https://user-images.githubusercontent.com/5808185/84895836-8e8c7300-b0c0-11ea-8a06-0a71eee6eb39.png">

```r
library(googlesheets4)
read_sheet("URL", sheet = "sheetname")

```

**Comment by jennybc** [comment]
The dev version of gargle now handles this error specifically, i.e. prints it nicely So you can consider the "please open an issue, so we can fix" as "already handled".

I can't make the error go away, because it really does mean the quota has been exhausted.

A couple of things you can try to see this less often:

  * Use your own API key and/or OAuth app, so you aren't sharing quota with the rest of the world's R users for whichever package we're talking about. Explained in https://gargle.r-lib.org/articles/get-api-credentials.html
  * If you're feeling adventurous, you can install from a development branch that is equipped with retry logic. Sometimes we have a wait a long time (100 seconds!) to resume working, but it does make a huge difference with automated work. Install via `devtools::install_github("r-lib/gargle@retry")`. This feature will make its way into the next gargle release.

**Comment by DataStrategist** [comment]
Hi Jenny (happy new year!), we are trying to set up our own API for sheets in order to avoid this error. We went to our GCP account, set up the API for google sheets, but at that point we're unclear on how to proceed. The above linked page says:

>From the Developers Console, in the target GCP Project, go to APIs & Services > Credentials.
> Do Create credentials > API key

But under "create credentials" we only see `OAuth client ID` or `Service account`. 

Given sheets seems to be a bit unique, I find the instructions on the gargle help page a bit obtuse. Is there, or would it be possible to create a baby vignette or step-by-step process to set up specifically this type of API access? I can help write it up if you can just show me how to do it.

Thanks!

**Comment by jennybc** [comment]
So you don't see this?

<img width="1030" alt="Screen Shot 2021-01-08 at 8 58 40 AM" src="https://user-images.githubusercontent.com/599454/104042781-c1e33c00-518f-11eb-9a9c-6ecd4790e1c7.png">

**Comment by DataStrategist** [comment]
Nope. But my left menu looks different than yours... what's that URL? 

![image](https://user-images.githubusercontent.com/8094091/104073548-e37f0a80-5205-11eb-8c4b-5747aa0a90fd.png)

**Comment by jennybc** [comment]
I'm at: `https://console.cloud.google.com/apis/credentials?project=MY_PROJECT`.

You look like you've somehow gotten there via an API-specific route? I.e. the left side and the URL all look specific to Sheets. This is a screen I have never seen before.

**Comment by jennybc** [comment]
I do what's in the [How to get your own API credentials](https://gargle.r-lib.org/articles/get-api-credentials.html)

Go to <https://console.cloud.google.com>.
...
From the Developers Console (*meaning the URL above*), in the target GCP Project, go to APIs & Services > Credentials.
Do Create credentials > API key.

**Comment by DataStrategist** [comment]
Yup! Found the feature using the link you specified. I think we had accessed that page via the sheets API. Anyway... since our files we need to access are private but on the user's Drive (as opposed to on the service account's Drive), we can't use the API for now... I'm going to have to read the documentation fully at another time. Thanks!

**Comment by jennybc** [comment]
> since our files we need to access are private but on the user's Drive (as opposed to on the service account's Drive), we can't use the API for now

I don't follow this. What service account? We've been talking about setting up an API key and, presumably, OAuth client. I think you might be right that you have some misunderstandings about how auth works and how it intersects with your goal. Hopefully you'll be able to revisit this later and work it out.
