### ISSUE TITLE
Using .auth <<- gargle::init_AuthState inside own package (This is not allowed by the CRAN policies.)

### ISSUE THREAD

**Issue by selesnow** [r-lib/gargle#184]
Hello Jenny, i try to use next example from [googledrive](https://github.com/tidyverse/googledrive/blob/545bfe1f30cca9f005be7091a0b56547ed09506c/R/zzz.R#L3), [bigrquery](https://github.com/r-dbi/bigrquery/blob/main/R/zzz.R#L3) and [googlesheets4](https://github.com/tidyverse/googlesheets4/blob/master/R/aaa.R#L3) packages in my own [rgoogleads](https://github.com/selesnow/rgoogleads/blob/master/R/zzz.R#L4) for use internal object of class `gargle::AuthClass`.

Example from my [package](https://github.com/selesnow/rgoogleads/blob/master/R/zzz.R#L4)

```
.onLoad <- function(libname, pkgname) {

  # auth object
  .auth <<- gargle::init_AuthState(
    package     = "rgoogleads",
    auth_active = TRUE
  )
```

But, when i try send my package into CRAN i get answer from Julia Haider:

> Please do not modify the global environment (e.g. by using <<-) in your
> functions. This is not allowed by the CRAN policies.

Help me please, what did I do wrong?

**Comment by jennybc** [comment]
Your use of `<<-` is fine here, but it's not immediately easy for the CRAN reviewer see that.

It's OK because you are modifying the value of `.auth`, a pre-existing object in your package's namespace. (I'm assuming that, like all the packages you are using as reference, you have `.auth <- NULL` elsewhere.)

However, it would be good to eliminate this pattern that sets off CRAN's alarm bells. I discussed with colleagues and got a few ideas. Here's one I just implemented in googledrive, that seems like it might be a good option for all of us:

``` r
.onLoad <- function(libname, pkgname) {

  # .auth is created in R/drive_auth.R
  # this is to insure we get an instance of gargle's AuthState using the
  # current, locally installed version of gargle
  utils::assignInMyNamespace(
    ".auth",
    gargle::init_AuthState(package = "googledrive", auth_active = TRUE)
  )
}
```

https://github.com/tidyverse/googledrive/commit/9a0334e89f7ab78f7f83e9a524131b4c08c126a6

Summary:

* You still need to create `.auth <- NULL` somewhere. Historically I've done this in `R/PKG_auth.R`. But another sensible place is right above the definition of `.onLoad()`. Either way, you probably need a comment to/from these two locations, explaining what's going on in the other place.
* Instead of using `<<-` in `.onLoad()` to initialize `.auth`, call `utils::assignInMyNamespace()`. This makes the intent very clear.
* Make sure the utils package is listed in the `Imports:` section of your `DESCRIPTION` file.

You could also leave your code alone, move the `.auth <- NULL` to the same file as `.onLoad()`, place it right above, make it easy to see what you're doing, and explain that your use of `<<-` is only modifying an object in your own namespace.

But I think I'd recommend taking the `assignInMyNamespace()` approach.

**Comment by jennybc** [comment]
A second approach described by @jeroen also works, so I want to document it here.

In `.onLoad()`, you could include code like:

``` r
  # this is to insure we get an instance of gargle's AuthState using the
  # current, locally installed version of gargle
  assign(
    ".auth",
    gargle::init_AuthState(package = "googledrive", auth_active = TRUE),
    environment(.onLoad)
  )
```

The advantage of this is that you **don't** need to pre-define `.auth` elsewhere. I would still have a comment in `R/PKG_auth.R` explaining where `.auth` is setup.

**Comment by jennybc** [comment]
This was good to explore and document, but also doesn't require any action in gargle.

**Comment by selesnow** [comment]
@jennybc thanks a lot! 

> (I'm assuming that, like all the packages you are using as reference, you have .auth <- NULL elsewhere.)

Yes, in [this row](https://github.com/selesnow/rgoogleads/blob/master/R/gads_auth.R#L5)
