### ISSUE TITLE
gargle:::secret_pw_name generates names that are invalid to serve as repository var on GitHub.

### ISSUE THREAD

**Issue by harell** [r-lib/gargle#203]
* Github secret names can only contain alphanumeric characters ([a-z], [A-Z], [0-9]) or underscores (_)
* R package names cannot contain underscores (_), but can contain dots (.)
* Some R packages names use a dot (.) to separate between words, for example [`github.observatory`](https://github.com/harell/github.observatory)
* In the case of `github.observatory`, `gargle:::secret_pw_name`  returns **GITHUB.OBSERVATORY_PASSWORD**.
* Passing **GITHUB.OBSERVATORY_PASSWORD** as a Github secret name prompts the following error:
![image](https://user-images.githubusercontent.com/7226303/163497938-4f0bdc1c-d62c-4376-b17b-274c609560de.png)

One suggestion is to make standardise R packages names such that dots are replaced with underscores.
For example, `gargle:::secret_pw_name(github.observatory)` will return `GITHUB_OBSERVATORY_PASSWORD` instead of `GITHUB.OBSERVATORY_PASSWORD`

**Comment by jennybc** [comment]
I think the real answer to this is to use the helpers in httr2, which grew out of the helpers here, but are less special case-y (gargle's functions also make very strong assumptions about the project being a *package*, which may not be the case).

https://httr2.r-lib.org/reference/secrets.html

In the long run, when/if gargle pivots from httr to httr2, I think it will defer to httr2's functions over its own.

I note that `GITHUB_OBSERVATORY_PASSWORD` also isn't going to work because:

> Names must not start with the `GITHUB_` prefix.

https://docs.github.com/en/actions/security-guides/encrypted-secrets#naming-your-secrets

But for the package case, it seems pretty low-stakes to make the substitution, which I'll do.
